---
title: "Mamíferos de la Gran Área Metropolitana (GAM) de Costa Rica"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(sf)
library(leaflet)
library(knitr)
library(kableExtra)

# Registros de presencia de Mammalia
registros_presencia_mammalia = st_read("https://raw.githubusercontent.com/atlas-servicios-ecosistemicos-gam/datos/master/biodiversidad/presencia/mammalia.geojson")

```

Column {data-width=500}
-----------------------------------------------------------------------

### Mapa de distribución

```{r}
leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery, group = "Imágenes de ESRI") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Stamen Toner Lite") %>%
  addProviderTiles(providers$OpenStreetMap.Mapnik, group = "OpenStreetMap") %>%
  addCircleMarkers(data = registros_presencia_mammalia,
                   stroke = F,
                   radius = 4,
                   fillColor = 'red',
                   fillOpacity = 1,
                   popup = paste(registros_presencia_mammalia$order, registros_presencia_mammalia$species, sep = '<br/>')) %>%
  addLayersControl(baseGroups = c("OpenStreetMap", "Stamen Toner Lite", "Imágenes de ESRI")) %>%
  addMiniMap(
    toggleDisplay = TRUE,
    tiles = providers$Stamen.TonerLite
  )
```

Column {data-width=500}
-----------------------------------------------------------------------

### especies de _Mammalia_ (mamíferos)
```{r}
valueBox(length(unique(registros_presencia_mammalia[["species"]])), icon = "fa-pencil")
```

### Registros de presencia de especies
```{r}
# Se extraen las observaciones ordenadas por orden alfabético de especies
mammalia.orden <- order(registros_presencia_mammalia$species)
# Se genera un nuevo data frame ordenado
mammalia.ordenadoxespecie <- registros_presencia_mammalia[mammalia.orden,]
# Se formatea la tabla con el nuevo data frame
kable(
  mammalia.ordenadoxespecie[, c("species","genus","family","order","year")], 
) %>%
kable_styling() %>%
scroll_box(
  width = "600px", 
  height = "250px", 
  fixed_thead = TRUE
)
```